Enhance constant-folding during inlining (#24431)
Fixes #24420 (see
https://github.com/scala/scala3/issues/24420#issuecomment-3539228280 for
some context) and fixes #24412.

Expressions can be constant-folded during inlining, but it isn't easy to
determine which expressions qualify. For example, this works:

```scala
inline def g1(): Boolean =
  true

inline def g2(): Long =
  inline if g1() then 1L else 2L

@main def Test: Unit =
  assert(g2() == 1L)
```

And this works:

```scala
inline def f1(): Long =
  1L

inline def f2(): Long =
  inline val x = f1() + 1L
  x

@main def Test: Unit =
  assert(f2() == 2L)
```

But if we change the right‐hand side of `x` to just be `f1()`, then we
get an error:

```scala
inline def f1(): Long =
  1L

inline def f3(): Long =
  inline val x = f1()
  x

@main def Test: Unit =
  assert(f3() == 1L)
```

```
$ scala -S 3.7.4 test3.scala
Compiling project (Scala 3.7.4, JVM (17))
[error] ./test3.scala:9:10
[error] inline value must have a literal constant type
[error]   assert(f3() == 1L)
[error]          ^^^^
Compilation failed
```

The first two examples work because they rely on `ConstantValue`, which
always strips `Typed`:

https://github.com/scala/scala3/blob/96b1b83ff166be70cd8c5b1e2774580e52af4a3a/compiler/src/dotty/tools/dotc/ast/TreeInfo.scala#L1217-L1220

This PR makes the third example work too by:

1. Making constant-folding during inlining more permissive. In
particular we now allow unwrapping `Typed` trees in more places (it was
already done in `ConstantValue`, but not `constToLiteral`). This is
implemented via a new `inlinedConstToLiteral` function — a stronger
version of `constToLiteral` — that it is called in critical places in
the `Inliner` where a constant is required.

2. Applying this function in two additional locations during inlining:
on the result of inlined calls, and on the right-hand side of inline
values.

This PR does not affect constant folding outside inlining (see #24432
for that discussion). It also keeps the existing semantics of `inline
val`; it merely documents and strengthens the behavior already present.